services:
  - type: web
    name: portafolio-multimedia
    env: php
    plan: free
    buildCommand: ""
    startCommand: php -S 0.0.0.0:10000
    envVars:
      - key: DB_HOST
        value: dpg-d0hco2qdbo4c73d1ehf0-a
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: mi_base_g5lt
      - key: DB_USER
        value: mi_base_g5lt_user
      - key: DB_PASSWORD
        value: 8Y93y4VQ473D2qD8HNqFCEn23rbEdb5x
